/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/native'

export default function Character(props) {
  const { nodes, materials } = useGLTF(require('../assets/Models/BOY_CHARACTER.glb'))
  return (
    // <group {...props} dispose={null} scale={11} position={[1.9,-11,-5]}>
    <group {...props} dispose={null} scale={8} position={[0,-5.3,0]}>
      <mesh castShadow receiveShadow geometry={nodes.body_1.geometry} material={materials.shirt} />
      <mesh castShadow receiveShadow geometry={nodes.body_2.geometry} material={materials.shorts} />
      <mesh castShadow receiveShadow geometry={nodes.body_3.geometry} material={materials.shoe} />
      <mesh castShadow receiveShadow geometry={nodes.body_4.geometry} material={materials.hair} />
      <mesh castShadow receiveShadow geometry={nodes.body_5.geometry} material={materials.eye} />
      <mesh castShadow receiveShadow geometry={nodes.body_6.geometry} material={materials.body} />
      <mesh castShadow receiveShadow geometry={nodes.body_7.geometry} material={materials.head} />
    </group>
  )
}

useGLTF.preload(require('../assets/Models/BOY_CHARACTER.glb'))